# Commands

This file describes ideas how the labbook works and which commands are available. At the center of the labbook commands is a configuration file defining pipelines and dependencies

* Creation
- =labbook init project <template>=

  Create a new project from template. Comparable to =git init= with some extras like adding:
  1. a =.gitignore= file;
  2. a =.labbook.json= file;
  3. a =results= folder for archived results.

- =labbook init campaign <name>=

  Creates a new campaign folder with specified name and sets metadata, if folder exists subfolders are added to version control
  #+BEGIN_QUOTE
 base name results .gitignore .archive .config
  #+END_QUOTE

=- =labbook init campaign parameter_foo=

 base  parameter_foo results .gitignore .archive .config

- =labbook init new_base [parameter_foo/1] -m "Use parameter 1 for new base case"=

 base results .archive/old_base_id

* Execution
- =labook execute <pipeline> <campaign/case>=
  
  Execute the pipeline for a full campaign or a specific case. There are four different pipeline types:
  1. preprocessing:
      
    Brings a campaign or a case into an executable state.
  2. execution:
  
    Runs a simulation and sets the state to started. If copy flag is set the case is copied to a dedicated folder with the hash of the transforming function, otherwise only a simlink is created.
  3. postprocessing
  
    Extracts results from the cases and sets the state to complete. Initially, results are non-final, meaning they are added to the repo but flaged as non-final. Non final results can be purged easily or finallised and archived. 
    
  4. archive 
    
  A pipeline might be of multiple types
  
- =labook rebase <campaign/case>=

  Sets =campaign/case= as new base case, archives all other cases

* Log
  
- =labbook checkout <revision>=

  Go back to revision
  
- =labbook log=
 
  Shows a full log of the current project
  
- =labbook log [done/started/waiting]=
 
  Shows cases which are =completed/started/waiting=
  

  
- =labbook commit -m <message>=

  Commit state to version control. *TODO* Specify when it needed 
  #+BEGIN_QUOTE
  base results .gitignore .archive .config 
  #+END_QUOTE
